### ISSUE TITLE
Investigate sleep in attention_head

### ISSUE THREAD

**Issue by cdondrup** [LCAS/uol-openday-robot#20]
Why do we have to sleep in attention_head in order to allow the callback to jump in and set some variables?

**Comment by marc-hanheide** [comment]
Le me know if I can help with this. I've loads of horrible experience with multithreading in C++...

**Comment by pet1330** [comment]
I've been looking into it and I can't work out why it needs it, but it seems a lot of people when using lock guard also have a wait it their code. 

I've also added three new variables thread_x, thread_y, and thread_z because we thought this might save us from having to lock almost the whole function to only locking it then we're actually assigning the values. But this also seems like a bit of a hack extra variables. 

I was also temped to try unique_lock, instead of lock_guard to see if that makes a difference, maybe unlocking and locking manually at the end of each section might be faster than it being called in the destructor/constructor. 

Am I along the right lines?

**Comment by marc-hanheide** [comment]
question is: what is the problem in first place? Does it dead lock?

**Comment by cdondrup** [comment]
The problem is that we are using the feedback from our action to get the position of the person in relation to the robot and then turn Linda towards the closest person found. This is currently done using acrtan2 to set the angular velocities, continuously updating it over the feedback callback to stay interactive while talking. Problem is that on the sending site the update of the feedback is at a much higher frequency then cob updates which basically locks out cob from writing data most of the times and does make it terribly slow to respond.
Solution could be to only update the feedback when there is new data.

**Comment by cdondrup** [comment]
Now the execute callback does not continuously spam data any more and locks the variables in order to so but only sets the time until the locationCallback should stream data on the feedback topic. As mentioned this causes the execute callback to terminate immediately (see commit above).
But now only the time variable has to be thread safe and is only set once by the execute callback and then read by the locationCall as soon as there is new data to publish.
