### ISSUE TITLE
QT UI for displaying on the screen

### ISSUE THREAD

**Issue by pet1330** [LCAS/uol-openday-robot#22]
qt_ros doesn't have much documentation, but I found this and I'll try and work something out over the weekend to create a very simple UI.
- http://www.ros.org/wiki/qt_ros/Tutorials
- https://github.com/stonier/qt_ros

**Comment by cdondrup** [comment]
Since it is weekend I decided to have some "fun" and wrote a Qt based app for Linda which is basically just a touch screen emergency button: https://github.com/cdondrup/scitos_apps/tree/master/scitos_touch
This uses Qt and could be a nice example for your interaction GUI.
What I did to make it work:
- Create GUI and button callbacks with Qt Creator
- Create catkin package
- Copy .cpp, .h and .ui files into the repository file structure
- Adapt CMakeLists.txt and package.xml files. This is a bit tricky but you can just have a look at the CMakeLists file I have and adapt it to your needs which should just be renaming some entries to represent your file names.
- Fill in the ros functionalities not using Qt Creator but an editor of your choice (This is necessary because Qt Creator doesn't know the ros libraries and can't build any projects if you try to use ros funtionalities). Have a careful look at the ros_thread.h file in the include folder of my project. You can basically just take this and instead of calling the services like I did you have to use an actionlib based approach. This will spare you quite some trouble with the threading.

**Comment by marc-hanheide** [comment]
rockin' cool!

**Comment by marc-hanheide** [comment]
I just thought it might be a good idea to develop this as an RQT plugin. For the open day we then have a dedicated RQT session that can also display rviz and other useful GUIs in a comfortable way. Also, this would be the most ROS compatible way to do it. What do you think?

**Comment by cdondrup** [comment]
Might be a good Idea.
Maybe @pet1330 can have a look at: http://ros.org/wiki/rqt/Tutorials/Create%20your%20new%20rqt%20plugin after lunch and see if it is useful for creating an interaction GUI.

**Comment by marc-hanheide** [comment]
Looks pretty simple and exactly like what we want to me. I tend to replace "might" by "surely" ;-)

**Comment by marc-hanheide** [comment]
Btw, is there a smach plugin for RQT? Would come handy, too.

**Comment by cdondrup** [comment]
Not at the moment. It is currently under development: http://www.ros.org/wiki/rqt/Plugins
But it seems there hasn't been any significant progress.

**Comment by cdondrup** [comment]
To be able to be of help I just restructured and refactored my emergency button (linked above) into a rqt plugin. And because Marc is right and this is how it is supposed to be done in ros ;)
So if you want to put your Qt project into the right structure for rqt you can simply have a look at it and try. But as I said we can also sit together and restructure it.

**Comment by pet1330** [comment]
That's cool, I should have the GUI completely done by tomorrow lunch time in QT Designer. I'll have a look at your emergancy stop button RQT version after that and see if I can work it out. :)

**Comment by marc-hanheide** [comment]
I love it when I'm right ;-) thanks, @cdondrup

**Comment by cdondrup** [comment]
There was no point in denying it :D
But there is still one thing I don't really get: I don't know why I have to spin in order to get my subscriber to call the callback. I thought that rqt would take care of that but obviously it isn't or I did not find the right way to do it yet. The tutorial isn't mentioning anything and my google searches have been fruitless. Will investigate further.

**Comment by cdondrup** [comment]
What do you know? As soon as you do it right, it works...
If you use the right node handle you don't have to spin. I knew there was something fishy.

**Comment by marc-hanheide** [comment]
Just a comment: It is good practice to mention which commit on github actually closes the issue, so that people can track HOW something was fixed. I had to search quite a bit to find where this has been resolved. Same for other issues. As I said, not a biggie, just a suggestion for the future.

**Comment by pet1330** [comment]
Sorry! I'll make sure I do this next time. :)
